OCRTool/Controllers/TemplateController.cs
using Domain.Domain;
using Domain.Interface;
using Hangfire;
using Infrastructure.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OCRTool.Controllers
{
    [Authorize]
    public class TemplateController : Controller
    {
        // GET: Template
        ITemplateRepository TemplateRepository = new TemplateRepository();
        ISystemLogRepository SystemLogRepository = new SystemLogRepository();

        public ActionResult Index()
        {
            return View();
        }
        
        [CustomAuthorize("!STAFF")]
        public ActionResult AddEdit(int templateId = 0)
        {
            ViewBag.templateId = templateId;
            return View();
        }

        [CustomAuthorize("!STAFF")]
        public ActionResult AddTemplate(Template t, TemplateDetails[] tdArr)
        {
            t.CreatedBy = User.Identity.Name;
            t.CreatedOn = DateTime.Now;

            var systemLog = new SystemLog
            {
                User = User.Identity.Name,
                DTLog = DateTime.Now,
                Type = "TEMPLATE"
            };

            if (t.Id > 0)
            {
                systemLog.Description = $"The user updated the template {t.TemplateName} (" +
                    $"{t.Id}).";
            }
            else
            {
                systemLog.Description = $"The user added a new template {t.TemplateName}.";
            }

            var result = TemplateRepository.AddUpdateTemplate(t, tdArr);

            systemLog.Status = result.Status == "SUCCESS" ? "COMPLETED" : "FAILED";

            BackgroundJob.Enqueue(() => SystemLogRepository.AddSystemLog(systemLog));
            
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [CustomAuthorize("!STAFF")]
        public ActionResult ChangeTemplateStatus(int templateId, string templateName, bool willDisable)
        {
            var systemLog = new SystemLog
            {
                User = User.Identity.Name,
                DTLog = DateTime.Now,
                Type = "TEMPLATE",
                Description = $"The user {(willDisable == true ? "disabled" : "enabled")} the " +
                $"{templateName} template."
            };

            var result = TemplateRepository.ChangeTemplateStatus(templateId, willDisable);

            systemLog.Status = result == "SUCCESS" ? "COMPLETED" : "FAILED";

            BackgroundJob.Enqueue(() => SystemLogRepository.AddSystemLog(systemLog));

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [CustomAuthorize("!STAFF")]
        public ActionResult SaveTemplateFile(HttpPostedFileBase FileUpload, string templateId)
        {
            var result = "";

            try
            {
                var splitfilename = FileUpload.FileName.Split('.');
                var fileExtension = splitfilename[splitfilename.Length - 1];

                FileUpload.SaveAs(Server.MapPath("~/Template Files/" + templateId + "." + fileExtension));

                result = "SUCCESS";
            }
            catch (Exception ex)
            {
                result = ex.Message;
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetTemplateList(bool includeDisabled = false)
        {
            return Json(TemplateRepository.GetTemplateList(includeDisabled), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetTemplateInfo(int templateId) {
            TemplateInfo ti = new TemplateInfo {
                Template = TemplateRepository.GetTemplateById(templateId),
                TemplateDetails = TemplateRepository.GetTemplateDetails(templateId)
            };

            return Json(ti, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetTemplateDetails(int templateId)
        {
            return Json(TemplateRepository.GetTemplateDetails(templateId), JsonRequestBehavior.AllowGet);
        }

        public class TemplateInfo {
            public Template Template { get; set; }
            public List<TemplateDetails> TemplateDetails { get; set; }
        }
    }
}

OCRTool/Views/Template/AddEdit.cshtml
@{
    Layout = "~/Views/Shared/_TemplateLayout.cshtml";
}

@section scripts {
    <script>
        var templateIdparam = @ViewBag.templateId;
    </script>
    <script src=@Url.Content("~/Scripts/jquery.color.js") type="text/javascript"></script>
    <script src=@Url.Content("~/Scripts/jquery.Jcrop.min.js") type="text/javascript"></script>
    <script src=@Url.Content("~/Scripts/pdf.worker.js") type="text/javascript"></script>
    <script src=@Url.Content("~/Scripts/pdf.js") type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/pages/addedittemp.js")" type="text/javascript"></script>
}

@section styles {
    <link href="@Url.Content("~/Content/jquery.Jcrop.min.css")" rel="stylesheet" type="text/css" />

    <style>
        #canvas-file, .field-container.active {
            position: sticky;
            z-index: 101;
        }

        #overlay {
            position: fixed; /* Sit on top of the page content */
            display: none; /* Hidden by default */
            width: 100%; /* Full width (cover the whole page) */
            height: 100%; /* Full height (cover the whole page) */
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: rgba(0,0,0,0.5); /* Black background with opacity */
            z-index: 100; /* Specify a stack order in case you're using a different order for other elements */
            cursor: pointer; /* Add a pointer on hover */
        }

        #fields-container .field-container:nth-child(1) {
            margin-top: 20px;
        }

        .field-container {
            padding: 10px 10px !important;
        }

            .field-container.active {
                background: white;
                border: 1px solid #1E1E2D
            }

        .btnSaveField {
            width: 55px;
            height: 29px;
            font-size: 11px;
        }

        .btnRemoveCoordinate {
            width: 75px;
            height: 29px;
            font-size: 11px;
            margin-left:5px;
        }

        .field-name input {
            width: 100%;
            max-width: 155px;
        }

        .field-container > div + div {
            margin-bottom: 5px;
        }

        .locate {
            margin-top: 12px;
        }

        .btnLocate {
            height: 32px !important;
            width: 70px;
            font-size: 12px !important;
        }

        #btnNext:hover, #btnPrev:hover {
            cursor: pointer;
            color: #5867DD;
            text-decoration: underline;
        }

        .label {
            font-size: 15px;
        }
    </style>
}

<div style="padding: 10px 15px 0; min-height: 90%;" class="w-100 clearfix">
	<div>
		<p style="border-bottom: 1px solid #f2f2f2; margin-bottom: 13px; padding-bottom: 13px;">
			<a href="@Url.Action("Index", "Template")" class="mr-1"><< Back</a>
			<span class="mr-1">&bull;</span>
			<span class="mr-1"><i class="flaticon2-document"></i> Templates</span>
			<span class="mr-1">&bull;</span>
			<span id="mode">Add</span>
		</p>
	</div>
	<div class="col-md-12 text-right">
		<button id="btnSaveTemplate" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Save template</button>
	</div>
	<div class="w-100 clearfix">
		<div class="d-flex">
            <div id="set-area" class="col-4">
                <div class="d-flex align-items-center">
                    <div style="width:90%;">
                        <label for="cbxDocumentType">Document Type : </label>
                        <select class="form-control form-control-sm " id="cbxDocumentType">
                            <option disabled hidden selected>Please select one</option>
                        </select>
                    </div>
                </div>
                <div class="d-flex align-items-center mt-4">
                    <div style="width:90%;">
                        <label for="txtTemplateName">Template Name : </label>
                        <div class="kt-input-icon kt-input-icon--left">
                            <input class="form-control form-control-sm" autocomplete="off" id="txtTemplateName" />
                            <span class="kt-input-icon__icon kt-input-icon__icon--left">
                                <span><i class="la la-file-text"></i></span>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 d-flex" style="padding: 0; width: 90%; border-top: 1px dotted #cecece; padding-top: 20px; margin-top: 40px;">
                    <div class="col-md-6" style="padding: 0;">
                        <span class="mr-3 mb-0 font-weight-bold" style="text-decoration: underline;">Add Fields </span>
                    </div>
                    <div class="col-md-6 text-right" style="padding: 0;">
                        <a href="javascript:void(0);" id="btnAddField"><i class="fa fa-plus-circle"></i> Add</a>
                    </div>
                </div>
                <div id="fields-container">

                </div>
            </div>

				<div id="file-area" style="border-left: #ccc solid 1px;" class="col-8">
                    <div>
                        <div>
                            <label>Browse the template file</label>
                            <div class="d-flex align-items-center justify-content-between">
                                <div class="col-10">
                                    <form enctype="multipart/form-data" method="post" autocomplete="off" id="frmFile">
                                        <fieldset>
                                            <input accept="image/*, .pdf" id="fileTemplate" type="file" class="form-control form-control-sm" />
                                        </fieldset>
                                    </form>
                                </div>
                                <div id="page-config-area" class="d-none align-items-center col-2 justify-content-center">
                                    <div>
                                        <i id="btnPrev" class="kt-menu__link-icon flaticon2-fast-back"></i>
                                    </div>
                                    <div class="mx-3">
                                        <label id="lblPageDetails" class="mb-0">1 of 2</label>
                                    </div>
                                    <div>
                                        <i id="btnNext" class="kt-menu__link-icon flaticon2-fast-next"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="file-container" class="overflow-auto mt-3" style="position:relative;z-index:220;">
                            <div id="file-preview" style="display:flex;justify-content:center;border:#ccc solid 1px;padding: 10px 20px;">
                                <div>
                                    <canvas id="canvas-file"></canvas>
                                </div>
                            </div>
                            <div style="z-index:250;background-repeat:no-repeat;position:absolute;border:solid red 1px;" id="img-preview">

                            </div>
                        </div>
                        
                    </div>
				</div>
			</div>
		</div>
	</div>
	<div id="overlay"></div>

OCRTool/Views/Template/Index.cshtml
@{
    Layout = "~/Views/Shared/_MetronicLayout.cshtml";
}

<div>
    <p>
        <span class="mr-1">Templates</span>
        <span class="mr-1">&bull;</span>
        <span>Index</span>
    </p>
</div>
<div class="kt-portlet">
    <div class="kt-portlet__head">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="flaticon2-document"></i>
            </span>
            <h4>
                List of Templates
            </h4>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-actions">
                @if (!User.IsInRole("STAFF"))
                {
                    <button id="btnAdd" onclick="window.location.href='@Url.Action("AddEdit", "Template")'"
                            class="btn btn-sm btn-primary">
                        Add New Template
                    </button>
                }
            </div>
        </div>
    </div>
    <div class="kt-portlet__body">
        <table class="table table-bordered" id="dtTemplate">
            <thead>
                <tr>
                    <td>Template</td>
                    <td>Document Type</td>
                    <td>Created By</td>
                    <td>Created On</td>
                    <td>Status</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="modalTemplate" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" style="max-width:80%;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"> <strong>View File</strong></h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="page-config-area" class="d-none align-items-center mb-4 justify-content-center">
                    <div>
                        <i id="btnPrev" class="kt-menu__link-icon flaticon2-fast-back"></i>
                    </div>
                    <div class="mx-3">
                        <label id="lblPageDetails" class="mb-0">1 of 2</label>
                    </div>
                    <div>
                        <i id="btnNext" class="kt-menu__link-icon flaticon2-fast-next"></i>
                    </div>
                </div>

                <div id="legends" class="d-flex flex-wrap justify-content-center">

                </div>

                <div style="height:350px;overflow:auto;">
                    <div id="file-area" style="width:max-content">

                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


@section styles {
    <style>
        .table .fa {
            font-size: 10px !important;
        }

        .table .kt-badge {
            font-weight: 500 !important;
        }

        #btnNext:hover, #btnPrev:hover {
            cursor: pointer;
            color: #5867DD;
            text-decoration: underline;
        }
    </style>
}

@section scripts {
    <script>
    var isStaff = @if (User.IsInRole("STAFF"))
    {
        <text>true</text>
    }
    else {
        <text>false</text>
    }
    </script>

    <script src=@Url.Content("~/Scripts/pdf.worker.js") type="text/javascript"></script>
    <script src=@Url.Content("~/Scripts/pdf.js") type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/pages/template.js")" type="text/javascript"></script>
}